apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres-container
    image: nogsantos/postgres
    ports:
      - containerPort: 5432
    env:
      - name: DB_NAME
        value: "nogsantos"
      - name: DB_USER
        value: "postgres"
      - name: DB_PASS
        value: "123456"
